version: "2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: unless-stopped
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

      BOOTSTRAP_SERVER: localhost:9092
      KAFKA_TOPIC: test_topic

      KAFKA_DELETE_TOPIC_ENABLE: true
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=WARN,kafka.foo.bar=DEBUG'
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    volumes:
      - ./test.json:/tmp/test.json
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topic'
      kafka-topics --bootstrap-server kafka:29092 --topic new-topic --create --partitions 1 --replication-factor 1

      echo -e 'Successfully created the following topic:'
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Publish message in kafka topic'
      kafka-console-producer --bootstrap-server kafka:29092 --topic new-topic < /tmp/test.json

      echo -e 'View message in kafka topic'
      kafka-console-consumer --bootstrap-server kafka:29092 --topic new-topic --from-beginning
      "